# Generated by Django 4.1.4 on 2023-01-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_books_delete_dress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='size',
            new_name='name',
        ),
    ]
