# Generated by Django 4.1.4 on 2023-01-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_size_books_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.AddField(
            model_name='books',
            name='Publish_year',
            field=models.CharField(choices=[('1800-1900', '1800'), ('1900-2000', '1900'), ('2000-Now', '2000')], default='default', max_length=30),
        ),
    ]
