# Generated by Django 4.1.4 on 2023-01-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_books_publisher_books_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Publish_year',
            field=models.CharField(choices=[('1800', '1800-1900'), ('1900', '1900-2000'), ('2000', '2000-Now')], default='default', max_length=30),
        ),
    ]
