# Generated by Django 4.1.4 on 2023-01-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_books_publish_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name']},
        ),
    ]
