# Generated by Django 4.1.4 on 2023-01-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_books_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name'], 'verbose_name': 'My Library'},
        ),
    ]
